name: deploy-container

on:
  push:
    branches: [main]
    paths:
      - "apps/container/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS CLI
        uses: cshinyinc/action-aws-cli@v1.2

      - name: Upload to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
